-- 155. Polymorphic Association Alternative Implementation
SELECT COALESCE((4)::BOOLEAN::INTEGER, 0);

SELECT COALESCE((NULL)::BOOLEAN::INTEGER, 0);

SELECT (NULL)::BOOLEAN

SELECT (NULL)::BOOLEAN::INTEGER

SELECT (32432)::BOOLEAN

SELECT (32432)::BOOLEAN::INTEGER